# Generated by Django 3.2.9 on 2022-05-01 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=64)),
                ('casting_time', models.CharField(max_length=32)),
                ('range', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=32)),
                ('higher_levels', models.CharField(max_length=512)),
                ('attack', models.CharField(max_length=32)),
                ('saving_throw', models.CharField(max_length=32)),
                ('damage_type', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('components', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
            ],
        ),
    ]
