# Generated by Django 3.2.9 on 2022-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=32)),
                ("term", models.CharField(max_length=16)),
                ("year", models.IntegerField()),
                ("school", models.CharField(max_length=64)),
                ("role", models.CharField(max_length=32)),
            ],
        ),
    ]
