# Generated by Django 4.1.4 on 2022-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_alter_term_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slides", models.URLField(max_length=512)),
                ("source", models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="VideoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "video",
                    models.ManyToManyField(
                        related_name="tags",
                        related_query_name="tags",
                        to="homepage.video",
                    ),
                ),
            ],
        ),
    ]
