# Generated by Django 4.1.4 on 2022-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_video_videotag"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="code",
            field=models.URLField(default=".", max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="source",
            field=models.URLField(max_length=128),
        ),
    ]
