# Generated by Django 4.1.4 on 2022-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_video_code_alter_video_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videotag",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(
                related_name="video", related_query_name="video", to="homepage.videotag"
            ),
        ),
    ]
