# Generated by Django 4.1.4 on 2022-12-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_video_last_updated_video_views_alter_video_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="last_updated",
            new_name="last_update",
        ),
    ]
