# Generated by Django 4.1.4 on 2022-12-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_rename_last_updated_video_last_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="last_update",
            new_name="last_updated",
        ),
    ]
