# Generated by Django 4.1.4 on 2023-01-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_rename_last_update_video_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="video",
                related_query_name="video",
                to="homepage.videotag",
            ),
        ),
    ]
