# Generated by Django 4.1.4 on 2023-02-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="thumbnails/"),
        ),
    ]
